appOperator:
  version: "1.0.0"

appCatalog:
  name: ""
  title: ""
  description: ""
  logoURL: "http://giantswarm.com/catalog-logo.png"
  storage:
    URL: "https://giantswarm.github.com/changeme-catalog/"
  config:
    configMap:
      name: ""
      namespace: "default"
### Example Secret metadata ###
#    secret:
#      name: ""
#      namespace: "default"

configMap:
  values:

### Example Secret configuration structure ###
#secret:
#  values:
#    token: ""
