version: 2.1

orbs:
  architect: giantswarm/architect@5.2.0

workflows:
  build:
    jobs:
      - architect/go-test:
          context: architect
          name: go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          name: push-appcatalog-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "appcatalog"
          filters:
            tags:
              only: /^v.*/
