version: 2.1
orbs:
  architect: giantswarm/architect@0.8.13

workflows:
  build:
    jobs:
      - architect/go-build:
          context: architect
          name: go-build
          binary: appcatalog
          filters:
            tags:
              only: /^v.*/

      # build and push chart to app catalog
      - architect/push-to-app-catalog:
          context: architect
          name: push-appcatalog-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "appcatalog"
          filters:
            tags:
              only: /^v.*/              
