{{ if and .Values.appCatalog.config .Values.appCatalog.config.secret }}
{{ if and .Values.appCatalog.config.secret.managed .Values.appCatalog.config.secret.values }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "resource.secret.name" . }}"
  namespace: "{{ .Values.appCatalog.config.secret.namespace }}"
data:
  values: |
{{- toYaml .Values.appCatalog.config.secret.values | b64enc | nindent 4 }}
type: Opaque
{{ end -}}
{{ end -}}
