apiVersion: "application.giantswarm.io/v1alpha1"
kind: AppCatalog
metadata:
  name: "{{ .Values.appCatalog.name }}"
  labels:
    application.giantswarm.io/catalog-type: "{{ .Values.appCatalog.catalogType }}"
    app-operator.giantswarm.io/version: "{{ .Values.appOperator.version }}"
spec:
  title: "{{ .Values.appCatalog.title }}"
  description: "{{ .Values.appCatalog.description }}"
  logoURL: "{{ .Values.appCatalog.logoURL }}"
  storage:
    type: "helm"
    URL: "{{ .Values.appCatalog.storage.URL }}"
  {{- if or ( eq (include "configMapExists" .) "true" ) ( eq (include "secretExists" .) "true" ) }}
  config:
    {{- if eq (include "configMapExists" .) "true" }}
    configMap:
      name: "{{ include "resource.configmap.name" . }}"
      namespace: "{{ .Values.appCatalog.config.configMap.namespace }}"
    {{- end }}
    {{- if eq (include "secretExists" .) "true" }}
    secret:
      name: "{{ include "resource.secret.name" . }}"
      namespace: "{{ .Values.appCatalog.config.secret.namespace }}"
    {{- end }}
  {{- else }}
  config: {}
  {{- end }}
