apiVersion: "application.giantswarm.io/v1alpha1"
kind: AppCatalog
metadata:
  name: "{{ .Values.appCatalog.name }}"
  labels:
    application.giantswarm.io/catalog-type: "{{ .Values.appCatalog.catalogType }}"
    app-operator.giantswarm.io/version: "{{ .Values.appOperator.version }}"
spec:
  title: "{{ .Values.appCatalog.title }}"
  description: "{{ .Values.appCatalog.description }}"
  logoURL: "{{ .Values.appCatalog.logoURL }}"
  storage:
    type: "helm"
    URL: "{{ .Values.appCatalog.storage.URL }}"
  {{- if .Values.appCatalog.config }}
  config:
    {{- if and .Values.appCatalog.config .Values.appCatalog.config.configMap }}
    {{- if and .Values.appCatalog.config.configMap.managed .Values.appCatalog.config.configMap.values }}
    configMap:
      name: "{{ include "resource.configmap.name" . }}"
      namespace: "{{ .Values.appCatalog.config.configMap.namespace }}"
    {{- end }}
    {{- end }}
    {{- if and .Values.appCatalog.config .Values.appCatalog.config.secret }}
    {{- if and .Values.appCatalog.config.secret.managed .Values.appCatalog.config.secret.values }}
    secret:
      name: "{{ include "resource.secret.name" . }}"
      namespace: "{{ .Values.appCatalog.config.secret.namespace }}"
    {{- end }}
    {{- end }}
  {{- end }}
