{{ if .Values.appCatalog.config }}{{ if .Values.appCatalog.config.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.appCatalog.config.configMap.name }}"
  namespace: "{{ .Values.appCatalog.config.configMap.namespace }}"
data:
  values: |
{{- toYaml .Values.configMap.values | trim | nindent 4 }}
{{- end }}{{ end -}}
