{{ if and .Values.appCatalog.config .Values.appCatalog.config.secret }}
{{ if .Values.appCatalog.config.secret.managed }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "resource.secret.name" . }}"
  namespace: "{{ .Values.appCatalog.config.secret.namespace }}"
data:
{{ if .Values.appCatalog.config.secret.values }}
  values: |
{{- toYaml .Values.appCatalog.config.secret.values | b64enc | nindent 4 }}
type: Opaque
{{ end -}}
{{ end -}}
{{ end -}}
