{{ if and .Values.appCatalog.config .Values.appCatalog.config.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appCatalog.config.secret.name }}"
  namespace: "{{ .Values.appCatalog.config.secret.namespace }}"
data:
  values: {{ toYaml .Values.secret.values | b64enc | quote }}
type: Opaque
{{ end }}
