{{ if and .Values.appCatalog.config .Values.appCatalog.config.secret .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appCatalog.config.secret.name }}"
  namespace: "{{ .Values.appCatalog.config.secret.namespace }}"
data:
  values: |
{{- toYaml .Values.appCatalog.config.secret.values | b64enc | quote | nindent 4 }}
type: Opaque
{{ end -}}
